"""
TaxiWise — Model Loading
Load pre-trained models from models/*.pkl (generated by train_model.py).
No training happens here — training lives exclusively in train_model.py.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import streamlit as st
import joblib
from pathlib import Path
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor

_MODEL_PKL   = Path(__file__).parent.parent / "models" / "model.pkl"
_XGB_PKL     = Path(__file__).parent.parent / "models" / "xgb_model.pkl"

FEATURE_COLS = [
    "PULocationID", "hour", "dow", "month",
    "zone_total_trips", "avg_fare", "avg_distance", "avg_duration",
]
TARGET = "trip_count"

FEATURE_LABELS = {
    "PULocationID":      "Zone ID",
    "hour":              "Hour of Day",
    "dow":               "Day of Week",
    "month":             "Month",
    "zone_total_trips":  "Zone Total Trips",
    "avg_fare":          "Avg Fare ($)",
    "avg_distance":      "Avg Distance (mi)",
    "avg_duration":      "Avg Duration (min)",
}

# ── Regression model (LR / RF — main prediction) ─────────────────────────────

@st.cache_resource(show_spinner=False)
def load_regression_model() -> dict:
    """Load pre-trained regression model from models/model.pkl."""
    if not _MODEL_PKL.exists():
        st.warning("⚠️ קובץ המודל `models/model.pkl` לא נמצא.")
        st.info(
            "**למה זה קורה?**\n\n"
            "המודל לא אומן עדיין. הקובץ `models/model.pkl` נוצר רק לאחר הרצת "
            "סקריפט האימון — הוא לא נכלל אוטומטית.\n\n"
            "**כיצד לתקן:**\n"
            "1. פתח טרמינל בתיקיית הפרויקט\n"
            "2. הרץ: `python train_model.py`\n"
            "3. המתן להשלמה (~1-2 דקות)\n"
            "4. דחוף ל-GitHub:\n"
            "```\n"
            "git add models/\n"
            "git commit -m 'Add trained model pkl'\n"
            "git push\n"
            "```"
        )
        st.stop()
    return joblib.load(_MODEL_PKL)


def predict_regression(payload: dict, features: dict) -> float:
    model     = payload["model"]
    scaler    = payload["scaler"]
    feat_cols = payload["feature_cols"]
    X = np.array([[features[f] for f in feat_cols]], dtype=float)
    if scaler is not None:
        X = scaler.transform(X)
    return float(max(model.predict(X)[0], 0.0))


# ── XGBoost model (Zone Recommendations) ─────────────────────────────────────

@st.cache_resource(show_spinner=False)
def load_xgb_model():
    """Load pre-trained XGBoost model from models/xgb_model.pkl."""
    if not _XGB_PKL.exists():
        st.warning("⚠️ קובץ המודל `models/xgb_model.pkl` לא נמצא.")
        st.info(
            "**למה זה קורה?**\n\n"
            "מודל ה-XGBoost לא אומן עדיין.\n\n"
            "**כיצד לתקן:**\n"
            "1. הרץ: `python train_model.py`\n"
            "2. דחוף ל-GitHub:\n"
            "```\n"
            "git add models/\n"
            "git commit -m 'Add trained model pkl'\n"
            "git push\n"
            "```"
        )
        st.stop()
    p = joblib.load(_XGB_PKL)
    return p["model"], p["metrics"], p["feature_importance"], p["y_test"], p["y_pred"]


# ── XGBoost training (called only from train_model.py) ───────────────────────

def _train(demand: pd.DataFrame):
    """Train XGBoost on demand data. Called by train_model.py, not by the app."""
    df = demand.dropna(subset=FEATURE_COLS + [TARGET])
    X  = df[FEATURE_COLS].values
    y  = df[TARGET].values.astype(float)

    X_tr, X_te, y_tr, y_te = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    model = XGBRegressor(
        n_estimators     = 100,
        max_depth        = 6,
        learning_rate    = 0.05,
        subsample        = 0.8,
        colsample_bytree = 0.8,
        min_child_weight = 3,
        random_state     = 42,
        n_jobs           = -1,
        verbosity        = 0,
    )
    model.fit(X_tr, y_tr)

    y_pred = np.maximum(model.predict(X_te), 0)

    metrics = {
        "mae":     mean_absolute_error(y_te, y_pred),
        "rmse":    float(np.sqrt(mean_squared_error(y_te, y_pred))),
        "r2":      r2_score(y_te, y_pred),
        "n_train": len(X_tr),
        "n_test":  len(X_te),
    }

    fi = (
        pd.DataFrame({
            "feature":    FEATURE_COLS,
            "label":      [FEATURE_LABELS[f] for f in FEATURE_COLS],
            "importance": model.feature_importances_,
        })
        .sort_values("importance", ascending=False)
        .reset_index(drop=True)
    )

    return model, metrics, fi, y_te, y_pred


# ── Hot-zone ranking (used by Zone Recommendations page) ─────────────────────

def predict_single(
    model,
    loc_id: int, hour: int, dow: int, month: int,
    zone_total: float, avg_fare: float, avg_dist: float, avg_dur: float,
) -> float:
    X = np.array([[loc_id, hour, dow, month, zone_total, avg_fare, avg_dist, avg_dur]])
    return float(max(model.predict(X)[0], 0))


def get_hot_zones(
    model,
    demand: pd.DataFrame,
    zones: pd.DataFrame,
    hour: int,
    dow: int,
    month: int,
    top_n: int = 10,
) -> pd.DataFrame:
    mask = (
        (demand["hour"] == hour) &
        (demand["dow"]  == dow)  &
        (demand["month"] == month)
    )
    cands = demand[mask].copy()

    if cands.empty:
        cands = (
            demand[demand["hour"] == hour]
            .groupby("PULocationID", as_index=False)
            .agg(
                avg_fare        =("avg_fare",        "mean"),
                avg_distance    =("avg_distance",    "mean"),
                avg_duration    =("avg_duration",    "mean"),
                zone_total_trips=("zone_total_trips", "first"),
            )
        )
        cands["hour"]  = hour
        cands["dow"]   = dow
        cands["month"] = month

    if cands.empty:
        return pd.DataFrame()

    cands = cands.dropna(subset=FEATURE_COLS)
    cands["predicted_demand"] = np.maximum(
        model.predict(cands[FEATURE_COLS]), 0
    )

    result = (
        cands
        .nlargest(top_n, "predicted_demand")
        [["PULocationID", "predicted_demand", "avg_fare",
          "avg_distance", "avg_duration", "zone_total_trips"]]
        .reset_index(drop=True)
    )
    result.index = range(1, len(result) + 1)

    z_lookup = (
        zones[["LocationID", "Zone", "Borough"]]
        .rename(columns={"LocationID": "PULocationID"})
    )
    return result.merge(z_lookup, on="PULocationID", how="left")
